**Goal:** Predict whether a breast tumor is **Malignant (M)** or **Benign (B)** based on 30 numeric features from cell nucleus measurements.

- **Dataset:** UCI Breast Cancer Wisconsin — 569 samples, 33 columns
- **Type:** Binary classification

In [54]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/organizations/uciml/breast-cancer-wisconsin-data/data.csv

In [55]:
df = pd.read_csv('/kaggle/input/datasets/organizations/uciml/breast-cancer-wisconsin-data/data.csv')

In [56]:
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [57]:
print(df.shape)

(569, 33)

In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       569 non-null    int64
 1   diagnosis                569 non-null    object
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             569 non-null    float64
 15  area_se                  569 non-null    float64
 16  smoothness_se            569 non-null    float64
 17  compactness_se           569 non-null    float64
 18  concavity_se             569 non-null    float64
 19  concave points_se        569 non-null    float64
 20  symmetry_se              569 non-null    float64
 21  fractal_dimension_se     569 non-null    float64
 22  radius_worst             569 non-null    float64
 23  texture_worst            569 non-null    float64
 24  perimeter_worst          569 non-null    float64
 25  area_worst               569 non-null    float64
 26  smoothness_worst         569 non-null    float64
 27  compactness_worst        569 non-null    float64
 28  concavity_worst          569 non-null    float64
 29  concave points_worst     569 non-null    float64
 30  symmetry_worst           569 non-null    float64
 31  fractal_dimension_worst  569 non-null    float64
 32  Unnamed: 32              0 non-null      float64
dtypes: float64(31), int64(1), object(1)
memory usage: 146.8+ KB

In [59]:
df['diagnosis'].value_counts()

diagnosis
B    357
M    212
Name: count, dtype: int64

In [60]:
df["diagnosis"] = df["diagnosis"].replace({
    "B": 0,
    "M": 1
})

/tmp/ipykernel_127/1472057043.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["diagnosis"] = df["diagnosis"].replace({

In [61]:
# Drop the empty column
df = df.drop(columns=['Unnamed: 32'])

# Drop any rows with NaN values (if they exist)
df = df.dropna()

In [62]:
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,842302,1,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,842517,1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,84300903,1,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,84348301,1,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,84358402,1,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [63]:
df.drop(columns=['id'], inplace=True)
X = df.drop(columns=['diagnosis'])
y = df['diagnosis']

In [64]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)


scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [65]:
X_train

array([[-1.44075296, -0.43531947, -1.36208497, ...,  0.9320124 ,
         2.09724217,  1.88645014],
       [ 1.97409619,  1.73302577,  2.09167167, ...,  2.6989469 ,
         1.89116053,  2.49783848],
       [-1.39998202, -1.24962228, -1.34520926, ..., -0.97023893,
         0.59760192,  0.0578942 ],
       ...,
       [ 0.04880192, -0.55500086, -0.06512547, ..., -1.23903365,
        -0.70863864, -1.27145475],
       [-0.03896885,  0.10207345, -0.03137406, ...,  1.05001236,
         0.43432185,  1.21336207],
       [-0.54860557,  0.31327591, -0.60350155, ..., -0.61102866,
        -0.3345212 , -0.84628745]])

In [66]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [67]:
model = Sequential()

model.add(Dense(3, activation='relu', input_shape=(X_train.shape[1],)))
model.add(Dense(1, activation='sigmoid'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [68]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_7 (Dense)                 │ (None, 3)              │            93 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 1)              │             4 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 97 (388.00 B)

 Trainable params: 97 (388.00 B)

 Non-trainable params: 0 (0.00 B)

In [69]:
model.compile(loss='binary_crossentropy', optimizer='Adam', metrics=['accuracy'])

In [70]:
print(X_train.shape)

print(df.columns)

model.summary()

(455, 30)
Index(['diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst'],
      dtype='object')

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_7 (Dense)                 │ (None, 3)              │            93 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 1)              │             4 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 97 (388.00 B)

 Trainable params: 97 (388.00 B)

 Non-trainable params: 0 (0.00 B)

In [71]:
model.fit(X_train, y_train, epochs=50, validation_split=0.2)

Epoch 1/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.3764 - loss: 1.1947 - val_accuracy: 0.4066 - val_loss: 1.1750
Epoch 2/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.3929 - loss: 1.0436 - val_accuracy: 0.4176 - val_loss: 1.0221
Epoch 3/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.4038 - loss: 0.9195 - val_accuracy: 0.4396 - val_loss: 0.9024
Epoch 4/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.4176 - loss: 0.8234 - val_accuracy: 0.4396 - val_loss: 0.8071
Epoch 5/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.4588 - loss: 0.7450 - val_accuracy: 0.4725 - val_loss: 0.7408
Epoch 6/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5082 - loss: 0.6851 - val_accuracy: 0.5055 - val_loss: 0.6869
Epoch 7/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5687 - loss: 0.6396 - val_accuracy: 0.5385 - val_loss: 0.6413
Epoch 8/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6236 - loss: 0.6026 - val_accuracy: 0.5714 - val_loss: 0.6061
Epoch 9/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6566 - loss: 0.5742 - val_accuracy: 0.6154 - val_loss: 0.5771
Epoch 10/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6923 - loss: 0.5502 - val_accuracy: 0.7033 - val_loss: 0.5544
Epoch 11/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7253 - loss: 0.5299 - val_accuracy: 0.7143 - val_loss: 0.5367
Epoch 12/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7555 - loss: 0.5135 - val_accuracy: 0.7582 - val_loss: 0.5211
Epoch 13/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7720 - loss: 0.4986 - val_accuracy: 0.8242 - val_loss: 0.5093
Epoch 14/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8077 - loss: 0.4872 - val_accuracy: 0.8571 - val_loss: 0.4997
Epoch 15/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8297 - loss: 0.4769 - val_accuracy: 0.8681 - val_loss: 0.4922
Epoch 16/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8516 - loss: 0.4682 - val_accuracy: 0.8681 - val_loss: 0.4854
Epoch 17/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8764 - loss: 0.4600 - val_accuracy: 0.8791 - val_loss: 0.4799
Epoch 18/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8791 - loss: 0.4531 - val_accuracy: 0.8791 - val_loss: 0.4747
Epoch 19/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8874 - loss: 0.4467 - val_accuracy: 0.8681 - val_loss: 0.4698
Epoch 20/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8956 - loss: 0.4411 - val_accuracy: 0.8681 - val_loss: 0.4653
Epoch 21/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9093 - loss: 0.4360 - val_accuracy: 0.8681 - val_loss: 0.4611
Epoch 22/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9093 - loss: 0.4310 - val_accuracy: 0.8791 - val_loss: 0.4572
Epoch 23/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9176 - loss: 0.4264 - val_accuracy: 0.8791 - val_loss: 0.4535
Epoch 24/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9231 - loss: 0.4219 - val_accuracy: 0.8791 - val_loss: 0.4498
Epoch 25/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9313 - loss: 0.4176 - val_accuracy: 0.8791 - val_loss: 0.4462
Epoch 26/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9313 - loss: 0.4135 - val_accuracy: 0.8791 - val_loss: 0.4425
Epoch 27/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9368 - loss: 0.4095 - val_accuracy: 0.8901 - val_loss: 0.4391
Epoch 28/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9396 - loss: 0.4056 - val_accuracy: 0.9011 - val_loss: 0.4360
Epoch 29/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9396 - loss: 0.4021 - val_accuracy: 0.9011 - val_loss: 0.4327
Epoch 30/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9396 - loss: 0.3984 - val_accuracy: 0.9011 - val_loss: 0.4297
Epoch 31/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9451 - loss: 0.3951 - val_accuracy: 0.9011 - val_loss: 0.4266
Epoch 32/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9478 - loss: 0.3917 - val_accuracy: 0.9011 - val_loss: 0.4233
Epoch 33/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9505 - loss: 0.3884 - val_accuracy: 0.9011 - val_loss: 0.4202
Epoch 34/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9533 - loss: 0.3850 - val_accuracy: 0.9231 - val_loss: 0.4174
Epoch 35/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9588 - loss: 0.3819 - val_accuracy: 0.9231 - val_loss: 0.4146
Epoch 36/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9588 - loss: 0.3786 - val_accuracy: 0.9231 - val_loss: 0.4118
Epoch 37/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9615 - loss: 0.3755 - val_accuracy: 0.9341 - val_loss: 0.4091
Epoch 38/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9670 - loss: 0.3725 - val_accuracy: 0.9341 - val_loss: 0.4062
Epoch 39/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9670 - loss: 0.3695 - val_accuracy: 0.9341 - val_loss: 0.4035
Epoch 40/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9670 - loss: 0.3664 - val_accuracy: 0.9341 - val_loss: 0.4009
Epoch 41/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9670 - loss: 0.3635 - val_accuracy: 0.9341 - val_loss: 0.3984
Epoch 42/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9670 - loss: 0.3606 - val_accuracy: 0.9341 - val_loss: 0.3957
Epoch 43/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9670 - loss: 0.3577 - val_accuracy: 0.9341 - val_loss: 0.3930
Epoch 44/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9670 - loss: 0.3549 - val_accuracy: 0.9560 - val_loss: 0.3904
Epoch 45/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9698 - loss: 0.3521 - val_accuracy: 0.9560 - val_loss: 0.3879
Epoch 46/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9698 - loss: 0.3492 - val_accuracy: 0.9451 - val_loss: 0.3852
Epoch 47/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9698 - loss: 0.3464 - val_accuracy: 0.9451 - val_loss: 0.3827
Epoch 48/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9725 - loss: 0.3436 - val_accuracy: 0.9341 - val_loss: 0.3803
Epoch 49/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9725 - loss: 0.3409 - val_accuracy: 0.9451 - val_loss: 0.3778
Epoch 50/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9725 - loss: 0.3381 - val_accuracy: 0.9451 - val_loss: 0.3754

**Parameter counting:**

| Layer | Formula | Count |
|---|---|---|
| Dense(3) | 30 inputs × 3 neurons + 3 biases | **93** |
| Dense(1) | 3 inputs × 1 neuron + 1 bias | **4** |
| **Total** | | **97 parameters** |

In [72]:
model.layers[0].get_weights()

[array([[ 0.07366269,  0.0236989 , -0.24543677],
        [ 0.15068203,  0.4909604 ,  0.43578127],
        [ 0.34204507, -0.11859971,  0.46881863],
        [ 0.10613836, -0.21164717,  0.16784285],
        [ 0.13159898,  0.17403173,  0.17145796],
        [ 0.07658099,  0.32677254, -0.04059304],
        [-0.04746903, -0.17436339, -0.2241639 ],
        [-0.04907913,  0.4535283 ,  0.30952138],
        [-0.08795043, -0.06055092,  0.2852334 ],
        [-0.0909848 , -0.0461503 ,  0.13439846],
        [-0.20039436,  0.10696784,  0.08004776],
        [ 0.29141548,  0.07466169, -0.35246363],
        [ 0.07183346, -0.09475999,  0.45944333],
        [ 0.31964493,  0.26821366,  0.42797336],
        [-0.02483321, -0.12144257, -0.13819782],
        [-0.16806541,  0.19737129,  0.08169905],
        [-0.21715431, -0.04061104,  0.23639153],
        [ 0.4101871 ,  0.19544104, -0.39999938],
        [-0.24881211,  0.00088628, -0.15853868],
        [-0.2578178 , -0.30358106,  0.04678115],
        [ 0.1304462 ,  0.3146527 ,  0.53035617],
        [-0.03784969, -0.26823673,  0.3413422 ],
        [-0.06969531,  0.4391183 ,  0.05089484],
        [ 0.22809224,  0.46789217,  0.08362921],
        [ 0.25279248, -0.18119684,  0.04250891],
        [-0.26833686, -0.17679854,  0.01953747],
        [ 0.39826253, -0.21661983, -0.12915577],
        [ 0.15619172, -0.06436493,  0.42190412],
        [ 0.41834033, -0.03160822,  0.36428115],
        [ 0.22353508, -0.06808861,  0.21277897]], dtype=float32),
 array([-0.0558281 , -0.17257738, -0.03766225], dtype=float32)]

In [73]:
y_log = model.predict(X_test)

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step

In [74]:
y_pred = np.where(y_log>0.5,1,0)

In [78]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.956140350877193